services:
  postgres:
    image: postgres:15-alpine
    container_name: crp-postgres
    environment:
      POSTGRES_DB: crp_db
      POSTGRES_USER: giabao
      POSTGRES_PASSWORD: giabao123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - crp-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  crp-network:
    driver: bridge 